apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: verifywise-config-rule
spec:
  rules:
    - host: verifywise.local
      http:
        paths:
          - path: /api
            backend:
              service:
                name: verifywise-svc
                port:
                  number: 3000
            pathType: Prefix
          - path: /
            backend:
              service:
                name: verifywise-svc
                port:
                  number: 80
            pathType: Prefix
