apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ingress.yaml

patchesStrategicMerge:
  - configmap.yaml
  - set-resources.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated

secretGenerator:
  - name: verifywise-secret
    envs:
      - secrets.env
