apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verifywise-postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment the appropriate storageClassName for your environment:
  # For minikube (default):
  storageClassName: standard
  # For AWS EKS:
  # storageClassName: gp2
  # For GCP GKE:
  # storageClassName: pd-standard
