apiVersion: v1
kind: Service
metadata:
  name: verifywise-svc
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    # - name: api
    #   port: 3000
    #   protocol: TCP
    #   targetPort: 3000
  selector:
    app: verifywise
